name: Push to private repo

on:
  push:
    branches:
      - main

jobs:
  update-private-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Add repo and push local main to private main
        run: |
          git remote add privrepo ${{ secrets.PRIVATE_REPO_URL }}
          git push privrepo main
